package model;

public enum Genre {
    ART,
    EDUCATION,
    CLASSICALENGLISHLITERATURE,
    CLASSICALJAPANESELITERATURE,
    CLASSICALRUSSIANLITERATURE,
    NOVEL,
    HISTORY,
    PHILOSOPHY,
    SCIENCEFICTION,
    STORY,
    STUDY,
}
